### ISSUE TITLE
0.9.0 panics on rust-analyzer on windows

### ISSUE THREAD

**Issue by kjeremy** [RustSec/cargo-audit#131]
Windows 10 x64

Clone `https://github.com/rust-analyzer/rust-analyzer`
Run `RUST_BACKTRACE=1 cargo audit`

After reporting no vulnerable packages it says:

> thread 'main' panicked at 'called `Option::unwrap()` on a `None` value', src\libcore\option.rs:347:21
> stack backtrace:
>    0: git_filter_source_repo
>    1: git_filter_source_repo
>    2: git_filter_source_repo
>    3: git_filter_source_repo
>    4: git_filter_source_repo
>    5: git_filter_source_repo
>    6: git_filter_source_repo
>    7: git_filter_source_repo
>    8: <unknown>
>    9: <unknown>
>   10: <unknown>
>   11: <unknown>
>   12: <unknown>
>   13: <unknown>
>   14: <unknown>
>   15: <unknown>
>   16: <unknown>
>   17: <unknown>
>   18: <unknown>
>   19: <unknown>
>   20: <unknown>
>   21: git_filter_source_repo
>   22: git_filter_source_repo
>   23: git_filter_source_repo
>   24: <unknown>
>   25: git_libgit2_version
>   26: BaseThreadInitThunk
>   27: RtlUserThreadStart

**Comment by tarcieri** [comment]
Interesting. Looks like it might be `git2`-related?

**Comment by tangmi** [comment]
Can confirm seeing this in my own private repo. Not seeing the crash with a selection of other repos (`cbindgen`, `rust-bindgen`, `planeshift`, `spirv_cross`). Not sure what makes my repo different, but it is a virtual manifest with a checked-in lockfile and a `[patch.crates-io]` section, if that helps?

Also seeing it on `gfx` (no patch section, however), `webrender`.

**Comment by tarcieri** [comment]
@tangmi I reproed a panic on webrender, although it appears to be unrelated

**Comment by jmagnuson** [comment]
I faced a similar issue, with a different backtrace profile:

<details>
    <summary>full backtrace</summary>

```
$ RUST_BACKTRACE=full cargo audit
    Fetching advisory database from `https://github.com/RustSec/advisory-db.git`
      Loaded 48 security advisories (from /home/parallels/.cargo/advisory-db)
    Scanning Cargo.lock for vulnerabilities (208 crate dependencies)
     Success No vulnerable packages found
thread 'main' panicked at 'called `Option::unwrap()` on a `None` value', src/libcore/option.rs:347:21
stack backtrace:
   0:     0x55a551c4ff1b - backtrace::backtrace::libunwind::trace::hfe5db90796807973
                               at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.29/src/backtrace/libunwind.rs:88
   1:     0x55a551c4ff1b - backtrace::backtrace::trace_unsynchronized::h34b865a835594335
                               at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.29/src/backtrace/mod.rs:66
   2:     0x55a551c4ff1b - std::sys_common::backtrace::_print::h527254ae44989167
                               at src/libstd/sys_common/backtrace.rs:47
   3:     0x55a551c4ff1b - std::sys_common::backtrace::print::he85dd5ddddf46503
                               at src/libstd/sys_common/backtrace.rs:36
   4:     0x55a551c4ff1b - std::panicking::default_hook::{{closure}}::h847a2eb38b396f14
                               at src/libstd/panicking.rs:200
   5:     0x55a551c4fbf7 - std::panicking::default_hook::h2ca0f9a30a0e206b
                               at src/libstd/panicking.rs:214
   6:     0x55a551c50690 - std::panicking::rust_panic_with_hook::hffcefc09751839d1
                               at src/libstd/panicking.rs:477
   7:     0x55a551c50212 - std::panicking::continue_panic_fmt::hc0f142c930c846fc
                               at src/libstd/panicking.rs:384
   8:     0x55a551c500f6 - rust_begin_unwind
                               at src/libstd/panicking.rs:311
   9:     0x55a551c6f2fd - core::panicking::panic_fmt::h2daf88b2616ca2b2
                               at src/libcore/panicking.rs:85
  10:     0x55a551c6f23c - core::panicking::panic::h2d0bc53a963fb996
                               at src/libcore/panicking.rs:49
  11:     0x55a551aec301 - cargo_lock::lockfile::Lockfile::dependent_packages::hfb459c266412326a
  12:     0x55a551aeb8fb - cargo_lock::dependency::tree::Tree::add_dependencies::h890ef151e777f69f
  13:     0x55a551aeb7e4 - cargo_lock::dependency::tree::Tree::new::h97952126e4ba29e7
  14:     0x55a551aec36a - cargo_lock::lockfile::Lockfile::dependency_tree::hf4cd3710ee3e2143
  15:     0x55a551a568d6 - cargo_audit::presenter::Presenter::print_report::he0100ab151339724
  16:     0x55a551a62e66 - cargo_audit::auditor::Auditor::audit::h43787d7861ed6d62
  17:     0x55a551a56278 - <cargo_audit::commands::audit::AuditCommand as abscissa_core::runnable::Runnable>::run::h1d82b6e9c6a69439
  18:     0x55a551a467ba - abscissa_core::application::Application::run::h45839d5c3869a11f
  19:     0x55a551a37bfb - abscissa_core::application::boot::h1f5ca004892afca0
  20:     0x55a551a36566 - cargo_audit::main::hd28179f10a6172f1
  21:     0x55a551a46ff3 - std::rt::lang_start::{{closure}}::h09027389f3b3ceee
  22:     0x55a551c50093 - std::rt::lang_start_internal::{{closure}}::h447d8812e3ee306d
                               at src/libstd/rt.rs:49
  23:     0x55a551c50093 - std::panicking::try::do_call::h4a61cb372364c745
                               at src/libstd/panicking.rs:296
  24:     0x55a551c571ba - __rust_maybe_catch_panic
                               at src/libpanic_unwind/lib.rs:82
  25:     0x55a551c50b9d - std::panicking::try::hdf71f938885bca42
                               at src/libstd/panicking.rs:275
  26:     0x55a551c50b9d - std::panic::catch_unwind::h7e85dbf162b1611a
                               at src/libstd/panic.rs:394
  27:     0x55a551c50b9d - std::rt::lang_start_internal::h1e06cc26b9fc25ea
                               at src/libstd/rt.rs:48
  28:     0x55a551a36592 - main
  29:     0x7f71c0d92b97 - __libc_start_main
  30:     0x55a551a0edda - _start
  31:                0x0 - <unknown>
```
</details>

It looks like `cargo-lock` no longer likes my lockfile for some reason.

Interestingly, `--json` works without panic:
```
$ RUST_BACKTRACE=full cargo audit --json
{"database":{"advisory-count":48,"last-commit":"5beb8d4305a348c9a6af3b20c670f28d10eb13dd","last-updated":"2019-09-24T09:52:00Z"},"lockfile":{"dependency-count":208},"settings":{"target_arch":null,"target_os":null,"severity":null,"ignore":[],"informational_warnings":["unmaintained"]},"vulnerabilities":{"found":false,"count":0,"list":[]},"warnings":[]}
```

**Comment by tarcieri** [comment]
I just released v0.9.1, which I think fixes a common root cause to all of these problems. Mind testing it out and seeing if it fixes the issue?

**Comment by jmagnuson** [comment]
That fixed it for me, thanks 👍

**Comment by tarcieri** [comment]
Cool, will close this out. Please let me know if the problem persists.

**Comment by kjeremy** [comment]
I can confirm that 0.9.1 fixes the issue.

**Comment by tangmi** [comment]
can confirm as well, thanks!
